### PR TITLE
Make rat send without reply, if in pm

### PR DESCRIPTION
**Pull request by yallxe**
Now you can send fat rat without replying to message if you are in PM.

### CODE REVIEW

**Comment by KOT4N11** [comment]
@sourcery-ai[bot] пошел нахуй далбоеб

**Comment by KOT4N11** [comment]
@KOT4N11 .sq

**Comment by KOT4N11** [comment]
@KOT4N11

**Comment by Fl1yd** [comment]
@sourcery-ai[bot] че

**Pull request merged**
